export { gcWorktrees } from "./gc.js"
export type { WorktreeGcResult } from "./gc.js"
export { GitRepository } from "./repository.js"
export type { WorktreeOptions, WorktreeReference } from "./repository.js"
export { Worktree } from "./worktree.js"
export type { ProcessOutput } from "./client.js"
